#!/bin/bash

pkg=$1

script=scripts/00-$pkg.sh

if [[ -f $script ]]; then
  echo "$script does already exists"
else
  echo "#!/bin/bash" > $script
  echo "" >> $script
  echo "omarchy-pkg-add $pkg" >> $script
  chmod +x $script
  git add $script
fi
